name: main-workflow

on:
  push:
    branches: [ develop, main ]
  workflow_dispatch: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    environment: ${{
      github.ref == 'refs/heads/develop' && 'dev' ||
      github.ref == 'refs/heads/main' && 'qa' ||
      startsWith(github.ref, 'refs/tags/v') && 'prod' }}

    steps:
      - name: Download repository
        uses: actions/checkout@v4
      - name: Print files in directory
        run: |
          ls -la
      - name: Get version Node JS
        run: |
          make version
      - name: Print username for environment
        run: |
          echo ${{vars.USERNAME}}
      - name: Show database password
        run: |
          echo ${{secrets.DATABASE_PASS}}
      - name: Show username with makefile
        run: |
          make run USERNAME=${{vars.USERNAME}}