name: Test Github Actions

on:
  push:
    branches: [ main ]

jobs:
  run-ubuntu:
    name: Run steps in Ubuntu
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -la
      - run: |
          make version