name: github-action-test

on:
  push:
    branches: [ develop, main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    environment: ${{ github.ref == 'refs/heads/develop' && 'dev' || 'prod' }}

    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -la
      - run: |
          make version
      - run: |
          echo ${{vars.USERNAME}}
      - run: |
          make run USERNAME=${{vars.USERNAME}}