name: github-action-test

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -la
      - run: |
          make version
      - run: |
          make run USERNAME=${{vars.USERNAME}}