name: main-workflow

on:
  push:
    branches: [ develop, main ]
  workflow_dispatch:
    inputs:
      app-type:
        description: 'App type'
        default: backend
        required: true
        type: choice
        options:
        - backend
        - frontend

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    environment: ${{
      github.ref == 'refs/heads/develop' && 'dev' ||
      github.ref == 'refs/heads/main' && 'qa' ||
      startsWith(github.ref, 'refs/tags/v') && 'prod' }}
    steps:
      - name: Download repository
        uses: actions/checkout@v4
      - name: Print files in directory
        run: |
          ls -la
      - name: Get version Node JS
        run: |
          make version
      - name: Print username for environment
        run: |
          echo ${{vars.USERNAME}}
      - name: Show database password
        run: |
          echo ${{secrets.DATABASE_PASS}}
      - name: Show username with makefile
        run: |
          make run USERNAME=${{vars.USERNAME}}
      - name: Show input
        run: |
          echo ${{inputs.app-type}}
        if: ${{github.event_name == 'workflow_dispatch'}}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            Makefile

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    environment: ${{
      github.ref == 'refs/heads/develop' && 'dev' ||
      github.ref == 'refs/heads/main' && 'qa' ||
      startsWith(github.ref, 'refs/tags/v') && 'prod' }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Print files in directory
        run: |
          ls -la